

export const API_ENDPOINTS = {
    BASE_URL:'http://65.1.68.43:5000/',
    LOGIN:'/samurai/login',
    GET_ZONES: '/ride/zones/',
    GET_CITIES:'',
    INSERT_CITY:'',
    GET_USERS: 'api/samurai/users?role=Customer/',
    GET_ADMINS: 'api/samurai/users?role=Admin/',
    POSTS: '/api/posts',
    GET_VEHICLES:'',
    INSERT_VEHICLE:'',
    INSERT_EMPLOYEE: '/api/employees',
    GET_EMPLOYEES:'api/employees',
    GET_RIDES: '/ride/ride/getAllRides',
    GET_RIDE_DETAILS: '/ride/ride/getRideDetails',
    GET_BASEFARES: '/ride/basefares/getAllBaseFares',
    INSERT_BASEFARE:'',
    GET_DISTANCE_BASEFARES:'',
    INSERT_DISTANCE_BASEFARE:'',
    GET_SERVICES:'',
    INSERT_SERVICE:'',
    GET_REASONS:'',
    INSERT_CANCEL_REASONS:'',
    MAP_KEY:'AIzaSyCiuHFwgsvT0NVQrv20ufBKanB4EUb2Q4c',
    INSERT_ZONE:'/ride/zones/createZone',
    INSERT_ADMIN:'/ride/admins/createAdmin',
    // Add more endpoints as needed
  };
